#!/usr/bin/env python3
"""The ONLY sanctioned way to change known-deviations.txt.  It can only SHRINK.

⭐ AN ALLOWLIST THAT CAN GROW BY ITSELF IS NOT A TO-DO LIST.  IT IS A CERTIFICATE
   THAT RENEWS ITSELF.

I spent a day fixing reset values, and after each fix I regenerated known-deviations.txt
from the model's CURRENT state.  It felt tidy.  It meant that any NEW lie I introduced
was written straight into the allowlist as "UNTRIAGED" and the gate went green.

It caught up with me on the ChipIdea USB block: I added an ID-register switch to
chipidea_read(), which is mapped over BOTH the .misc window AND the .endpoint window,
so USBMODE started answering HWGENERAL and ENDPTFLUSH started answering HWTXBUF.  A
brand-new fabrication in four registers.  The gate saw it, and MY OWN REGENERATION
SCRIPT FILED IT AS KNOWN.

    "An independent whitelist doesn't merely MISS the bug -- IT CERTIFIES IT."
                                                        -- ollama_95_neutron
    ...and mine issued the certificate automatically, on my behalf, every time I ran it.

So: this script NEVER adds a line.

    * an allowlisted register that now MATCHES  -> the line is DELETED (the ratchet)
    * a mismatch that is NOT in the allowlist   -> REFUSED.  It is printed, and it is
                                                  a FAILURE.  A human classifies it,
                                                  by hand, with a reason.

Adding an entry is a decision.  Decisions are typed by people, not generated by
scripts, or they are not decisions.

    usage:  ./triage.py            # report; delete fixed lines; refuse new ones
            ./triage.py --shrink   # actually rewrite the file (deletions only)
"""
import collections
import json
import os
import subprocess
import sys
import threading

HERE = os.path.dirname(os.path.abspath(__file__))
QEMU = os.environ.get("QEMU", os.path.join(HERE, "..", "..", "build",
                                           "qemu-system-aarch64"))
OPS = {8: "readb", 16: "readw", 32: "readl", 64: "readq"}


def probe(golden):
    p = subprocess.Popen(
        ["timeout", "-s", "KILL", "180", QEMU, "-M", "imx91-11x11-evk",
         "-display", "none", "-accel", "qtest", "-qtest", "stdio",
         "-monitor", "none", "-serial", "none"],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL, text=True)

    def ask():
        try:
            p.stdin.write("".join("%s 0x%x\n" % (OPS[r.get("width", 32)], r["addr"])
                                  for r in golden))
            p.stdin.flush()
            p.stdin.close()
        except (BrokenPipeError, ValueError):
            pass

    threading.Thread(target=ask, daemon=True).start()
    vals = []
    try:
        while len(vals) < len(golden):
            line = p.stdout.readline()
            if not line:
                break
            if line.startswith("OK 0x"):
                vals.append(int(line.split()[1], 16))
    finally:
        p.kill()
        p.wait()
    return vals


def main():
    shrink = "--shrink" in sys.argv
    golden = json.load(open(os.path.join(HERE, "rm-golden.json")))
    vals = probe(golden)
    if len(vals) != len(golden):
        sys.exit("FAIL: asked %d questions, got %d answers." % (len(golden), len(vals)))

    def mask(r):
        return (1 << r.get("width", 32)) - 1

    mismatched = {(r["inst"], r["reg"])
                  for r, v in zip(golden, vals)
                  if (v & mask(r)) != (r["reset"] & mask(r))}
    model = {(r["inst"], r["reg"]): v for r, v in zip(golden, vals)}
    rm = {(r["inst"], r["reg"]): r for r in golden}

    lines = open(os.path.join(HERE, "known-deviations.txt")).read().splitlines()
    allowed, kept = set(), []
    for line in lines:
        body = line.split("#", 1)[0].strip()
        if not body:
            kept.append(line)
            continue
        parts = body.split(None, 2)
        key = (parts[0], parts[1])
        allowed.add(key)
        if key in mismatched:
            kept.append(line)          # still a deviation: the line stays
        # else: FIXED -> the line is dropped.  The ratchet.

    fixed = sorted(k for k in allowed if k not in mismatched)
    new = sorted(k for k in mismatched if k not in allowed)

    print("allowlist: %d entries · %d fixed · %d NEW" % (len(allowed), len(fixed), len(new)))

    if fixed:
        print("\n✅ FIXED -- these registers now MATCH the RM, so their lines are deleted:")
        for inst, reg in fixed[:20]:
            print("    %-22s %s" % (inst, reg))
        if len(fixed) > 20:
            print("    ... and %d more" % (len(fixed) - 20))

    if new:
        print("\n⛔ REFUSED -- %d register(s) disagree with the RM and are NOT allowlisted."
              % len(new))
        print("   THIS SCRIPT WILL NOT ADD THEM.  An allowlist that can grow by itself")
        print("   is a certificate that renews itself.  Classify each one BY HAND, with")
        print("   a reason -- DECISION / UNMODELLED -- or fix the model.")
        for inst, reg in new[:25]:
            r = rm[(inst, reg)]
            print("    %-22s %-24s @0x%08x  model=0x%08x  RM=0x%08x"
                  % (inst, reg, r["addr"], model[(inst, reg)], r["reset"]))
        if len(new) > 25:
            print("    ... and %d more" % (len(new) - 25))

    if shrink:
        if new:
            print("\nREFUSING to rewrite: fix or hand-classify the new lies first.")
            return 1
        open(os.path.join(HERE, "known-deviations.txt"), "w").write("\n".join(kept) + "\n")
        print("\nknown-deviations.txt SHRUNK by %d line(s).  It never grows." % len(fixed))

    return 1 if new else 0


if __name__ == "__main__":
    sys.exit(main())
