/* GENERATED by tests/imx91-reset-values/gen-clock-tree.py -- DO NOT EDIT.
 *
 * Source: Linux drivers/clk/imx/clk-imx93.c (root_array, parent_names).
 * Row count ASSERTED against IMX91RM.pdf (95 CLOCK_ROOTn_CONTROL rows).
 * Retyping a device fact is how you fabricate one.
 */
#ifndef HW_MISC_IMX93_CCM_ROOTS_H
#define HW_MISC_IMX93_CCM_ROOTS_H

typedef enum {
    IMX93_CLK_SRC_OSC_24M,
    IMX93_CLK_SRC_SYS_PLL_PFD0,
    IMX93_CLK_SRC_SYS_PLL_PFD0_DIV2,
    IMX93_CLK_SRC_SYS_PLL_PFD1,
    IMX93_CLK_SRC_SYS_PLL_PFD1_DIV2,
    IMX93_CLK_SRC_SYS_PLL_PFD2,
    IMX93_CLK_SRC_SYS_PLL_PFD2_DIV2,
    IMX93_CLK_SRC_AUDIO_PLL,
    IMX93_CLK_SRC_VIDEO_PLL,
    IMX93_CLK_SRC_ARM_PLL,
    IMX93_CLK_SRC_DRAM_PLL,
    IMX93_CLK_SRC_CLK_EXT1,
    IMX93_CLK_SRC__COUNT,
} IMX93ClkSrc;

/* parent_names[sel][CONTROL.MUX] -> source */
static const IMX93ClkSrc imx93_ccm_sel[9][4] = {
    /* LOW_SPEED_IO_SEL   */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0_DIV2, IMX93_CLK_SRC_SYS_PLL_PFD1_DIV2, IMX93_CLK_SRC_VIDEO_PLL },
    /* NON_IO_SEL         */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0_DIV2, IMX93_CLK_SRC_SYS_PLL_PFD1_DIV2, IMX93_CLK_SRC_SYS_PLL_PFD2_DIV2 },
    /* FAST_SEL           */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0, IMX93_CLK_SRC_SYS_PLL_PFD1, IMX93_CLK_SRC_SYS_PLL_PFD2 },
    /* AUDIO_SEL          */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_AUDIO_PLL, IMX93_CLK_SRC_VIDEO_PLL, IMX93_CLK_SRC_CLK_EXT1 },
    /* VIDEO_SEL          */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_AUDIO_PLL, IMX93_CLK_SRC_VIDEO_PLL, IMX93_CLK_SRC_SYS_PLL_PFD0 },
    /* TPM_SEL            */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0, IMX93_CLK_SRC_AUDIO_PLL, IMX93_CLK_SRC_CLK_EXT1 },
    /* CKO1_SEL           */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0, IMX93_CLK_SRC_SYS_PLL_PFD1, IMX93_CLK_SRC_AUDIO_PLL },
    /* CKO2_SEL           */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_SYS_PLL_PFD0, IMX93_CLK_SRC_SYS_PLL_PFD1, IMX93_CLK_SRC_VIDEO_PLL },
    /* MISC_SEL           */ { IMX93_CLK_SRC_OSC_24M, IMX93_CLK_SRC_AUDIO_PLL, IMX93_CLK_SRC_VIDEO_PLL, IMX93_CLK_SRC_SYS_PLL_PFD2 },
};

/* Indexed by clock-root slice (CONTROL at slice * 0x80).
 * IMX93_CCM_NO_SEL = the RM documents this slice but Linux does not
 * register it -- it has NO SOURCE and DOES NOT TICK.  A dropped table
 * row must never read back as a plausible frequency.
 */
#define IMX93_CCM_NO_SEL 0xff

static const uint8_t imx93_ccm_root_sel[95] = {
    [ 0] = 2,  /* a55_periph_root */
    [ 1] = 0,  /* a55_mtr_bus_root */
    [ 2] = 2,  /* a55_alt_root */
    [ 3] = 0,  /* m33_root */
    [ 4] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [ 5] = 0,  /* bus_wakeup_root */
    [ 6] = 0,  /* bus_aon_root */
    [ 7] = 2,  /* wakeup_axi_root */
    [ 8] = 0,  /* swo_trace_root */
    [ 9] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [10] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [11] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [12] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [13] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [14] = 0,  /* lptmr1_root */
    [15] = 0,  /* lptmr2_root */
    [16] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [17] = 5,  /* tpm2_root */
    [18] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [19] = 5,  /* tpm4_root */
    [20] = 5,  /* tpm5_root */
    [21] = 5,  /* tpm6_root */
    [22] = 2,  /* flexspi1_root */
    [23] = 0,  /* can1_root */
    [24] = 0,  /* can2_root */
    [25] = 0,  /* lpuart1_root */
    [26] = 0,  /* lpuart2_root */
    [27] = 0,  /* lpuart3_root */
    [28] = 0,  /* lpuart4_root */
    [29] = 0,  /* lpuart5_root */
    [30] = 0,  /* lpuart6_root */
    [31] = 0,  /* lpuart7_root */
    [32] = 0,  /* lpuart8_root */
    [33] = 0,  /* lpi2c1_root */
    [34] = 0,  /* lpi2c2_root */
    [35] = 0,  /* lpi2c3_root */
    [36] = 0,  /* lpi2c4_root */
    [37] = 0,  /* lpi2c5_root */
    [38] = 0,  /* lpi2c6_root */
    [39] = 0,  /* lpi2c7_root */
    [40] = 0,  /* lpi2c8_root */
    [41] = 0,  /* lpspi1_root */
    [42] = 0,  /* lpspi2_root */
    [43] = 0,  /* lpspi3_root */
    [44] = 0,  /* lpspi4_root */
    [45] = 0,  /* lpspi5_root */
    [46] = 0,  /* lpspi6_root */
    [47] = 0,  /* lpspi7_root */
    [48] = 0,  /* lpspi8_root */
    [49] = 0,  /* i3c1_root */
    [50] = 0,  /* i3c2_root */
    [51] = 2,  /* usdhc1_root */
    [52] = 2,  /* usdhc2_root */
    [53] = 2,  /* usdhc3_root */
    [54] = 3,  /* sai1_root */
    [55] = 3,  /* sai2_root */
    [56] = 3,  /* sai3_root */
    [57] = 6,  /* ccm_cko1_root */
    [58] = 7,  /* ccm_cko2_root */
    [59] = 6,  /* ccm_cko3_root */
    [60] = 7,  /* ccm_cko4_root */
    [61] = 0,  /* hsio_root */
    [62] = 0,  /* hsio_usb_test_60m_root */
    [63] = 0,  /* hsio_acscan_80m_root */
    [64] = 8,  /* hsio_acscan_480m_root */
    [65] = 2,  /* nic_axi_root */
    [66] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [67] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [68] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [69] = 2,  /* media_axi_root */
    [70] = 0,  /* media_apb_root */
    [71] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [72] = 4,  /* media_disp_pix_root */
    [73] = 4,  /* cam_pix_root */
    [74] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [75] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [76] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [77] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [78] = 0,  /* adc_root */
    [79] = 3,  /* pdm_root */
    [80] = 0,  /* tstmr1_root */
    [81] = 0,  /* tstmr2_root */
    [82] = 3,  /* mqs1_root */
    [83] = 3,  /* mqs2_root */
    [84] = 1,  /* audio_xcvr_root */
    [85] = 3,  /* spdif_root */
    [86] = 1,  /* enet1_qos_tsn_root */
    [87] = 0,  /* enet_timer_root */
    [88] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [89] = 1,  /* enet2_regular_root */
    [90] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [91] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [92] = IMX93_CCM_NO_SEL,  /* not registered by Linux */
    [93] = 0,  /* usb_phy_root */
    [94] = 8,  /* pal_came_scan_root */
};

#define IMX93_CCM_NUM_SLICES 95

static const char *const imx93_ccm_root_name[95] = {
    [ 0] = "a55_periph_root",
    [ 1] = "a55_mtr_bus_root",
    [ 2] = "a55_alt_root",
    [ 3] = "m33_root",
    [ 4] = NULL,
    [ 5] = "bus_wakeup_root",
    [ 6] = "bus_aon_root",
    [ 7] = "wakeup_axi_root",
    [ 8] = "swo_trace_root",
    [ 9] = NULL,
    [10] = NULL,
    [11] = NULL,
    [12] = NULL,
    [13] = NULL,
    [14] = "lptmr1_root",
    [15] = "lptmr2_root",
    [16] = NULL,
    [17] = "tpm2_root",
    [18] = NULL,
    [19] = "tpm4_root",
    [20] = "tpm5_root",
    [21] = "tpm6_root",
    [22] = "flexspi1_root",
    [23] = "can1_root",
    [24] = "can2_root",
    [25] = "lpuart1_root",
    [26] = "lpuart2_root",
    [27] = "lpuart3_root",
    [28] = "lpuart4_root",
    [29] = "lpuart5_root",
    [30] = "lpuart6_root",
    [31] = "lpuart7_root",
    [32] = "lpuart8_root",
    [33] = "lpi2c1_root",
    [34] = "lpi2c2_root",
    [35] = "lpi2c3_root",
    [36] = "lpi2c4_root",
    [37] = "lpi2c5_root",
    [38] = "lpi2c6_root",
    [39] = "lpi2c7_root",
    [40] = "lpi2c8_root",
    [41] = "lpspi1_root",
    [42] = "lpspi2_root",
    [43] = "lpspi3_root",
    [44] = "lpspi4_root",
    [45] = "lpspi5_root",
    [46] = "lpspi6_root",
    [47] = "lpspi7_root",
    [48] = "lpspi8_root",
    [49] = "i3c1_root",
    [50] = "i3c2_root",
    [51] = "usdhc1_root",
    [52] = "usdhc2_root",
    [53] = "usdhc3_root",
    [54] = "sai1_root",
    [55] = "sai2_root",
    [56] = "sai3_root",
    [57] = "ccm_cko1_root",
    [58] = "ccm_cko2_root",
    [59] = "ccm_cko3_root",
    [60] = "ccm_cko4_root",
    [61] = "hsio_root",
    [62] = "hsio_usb_test_60m_root",
    [63] = "hsio_acscan_80m_root",
    [64] = "hsio_acscan_480m_root",
    [65] = "nic_axi_root",
    [66] = NULL,
    [67] = NULL,
    [68] = NULL,
    [69] = "media_axi_root",
    [70] = "media_apb_root",
    [71] = NULL,
    [72] = "media_disp_pix_root",
    [73] = "cam_pix_root",
    [74] = NULL,
    [75] = NULL,
    [76] = NULL,
    [77] = NULL,
    [78] = "adc_root",
    [79] = "pdm_root",
    [80] = "tstmr1_root",
    [81] = "tstmr2_root",
    [82] = "mqs1_root",
    [83] = "mqs2_root",
    [84] = "audio_xcvr_root",
    [85] = "spdif_root",
    [86] = "enet1_qos_tsn_root",
    [87] = "enet_timer_root",
    [88] = NULL,
    [89] = "enet2_regular_root",
    [90] = NULL,
    [91] = NULL,
    [92] = NULL,
    [93] = "usb_phy_root",
    [94] = "pal_came_scan_root",
};

#endif
