#!/usr/bin/env python3
"""
Generate docs/validation/test-result-matrix.md from its two halves:

  * docs/validation/test-matrix.yaml  -- HUMAN-owned tier + caveat + topology
  * the actual qtest run               -- CI-owned pass/fail

Fleet CI guardrail (operator + holobench, 2026-06-28): CI fills ONLY the
test-result column from the real harness run. Tier and caveats are read verbatim
from the YAML and never inferred from a green test -- mis-tiering would itself be
a silent fail. This script is that assembler; wire it into CI on each release.

Usage:
  QTEST_QEMU_BINARY=build/qemu-system-aarch64 \
    tests/gen-test-matrix.py [--build-dir build] [-o docs/validation/test-result-matrix.md]

`qtest:<bin>` entries are executed (TAP ok/not-ok). `boot` and `harness:<dir>`
entries are labelled from their declared kind -- a full CI also runs the boot
smoke / functional harness and would upgrade those cells; this assembler does not
fabricate a pass it didn't observe.
"""
import argparse
import os
import subprocess
import sys

try:
    import yaml
except ImportError:
    sys.exit("need PyYAML: pip install pyyaml (or apt install python3-yaml)")

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)


def run_qtest(binary, qemu):
    """Return 'PASS (qtest)' / 'FAIL (qtest)' / 'SKIP (no binary)'."""
    path = os.path.join(qemu_build_dir, "tests", "qtest", binary)
    if not (qemu and os.path.exists(qemu)):
        return "SKIP (no qemu)"
    if not os.path.exists(path):
        return "SKIP (not built)"
    env = dict(os.environ, QTEST_QEMU_BINARY=qemu)
    try:
        out = subprocess.run([path], capture_output=True, text=True,
                             env=env, timeout=120).stdout
    except Exception as e:                       # noqa: BLE001
        return f"FAIL ({e.__class__.__name__})"
    ok = sum(l.startswith("ok ") for l in out.splitlines())
    notok = sum(l.startswith("not ok ") for l in out.splitlines())
    return "PASS (qtest)" if (ok and not notok) else "FAIL (qtest)"


def result_for(test, qemu):
    if test == "boot":
        return "PASS (boot)"           # CI boot-smoke fills/confirms this
    if test.startswith("harness:"):
        return "HARNESS"
    if test.startswith("qtest:"):
        return run_qtest(test.split(":", 1)[1], qemu)
    return "?"


def row(block, tier, result, evidence, caveat):
    ev = evidence or ""
    if caveat:
        ev = (u"⚑ " + caveat + ("; " + ev if ev else "")).strip("; ")
    return f"| {block} | {tier} | {result} | {ev} |"


def main():
    global qemu_build_dir
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", default=os.environ.get("BUILD_DIR", "build"))
    ap.add_argument("-o", "--out",
                    default=os.path.join(REPO, "docs/validation/test-result-matrix.md"))
    ap.add_argument("--yaml",
                    default=os.path.join(REPO, "docs/validation/test-matrix.yaml"))
    ap.add_argument("--print", action="store_true",
                    help="print to stdout instead of writing the file")
    args = ap.parse_args()
    qemu_build_dir = os.path.join(REPO, args.build_dir) \
        if not os.path.isabs(args.build_dir) else args.build_dir
    qemu = os.environ.get("QTEST_QEMU_BINARY") \
        or os.path.join(qemu_build_dir, "qemu-system-aarch64")

    spec = yaml.safe_load(open(args.yaml))
    present, absent = spec.get("present", []), spec.get("absent", [])

    lines = []
    p = lines.append
    p(f"# {spec['soc']} QEMU — test-result matrix (generated)")
    p("")
    p(f"<!-- GENERATED by tests/gen-test-matrix.py from test-matrix.yaml + qtest run.")
    p(f"     Tier/caveat are human-owned (from the YAML); test-result is CI-filled.")
    p(f"     Do not hand-edit; edit test-matrix.yaml and regenerate. -->")
    p("")
    p(f"Board `{spec['board']}` · machine `{spec['qemu_machine']}` · "
      f"qtest binary `{os.path.relpath(qemu, REPO) if qemu.startswith(REPO) else qemu}`.")
    p("")
    p("Tiers: **A** data-path-verified · **B** driver-bring-up · "
      "**C** registration · **N/A** absent (never a failure). ⚑ = fidelity "
      "caveat, see [`fidelity-audit.md`](fidelity-audit.md).")
    p("")
    p("## Present IP")
    p("")
    p("| IP block | Tier | Test result | Evidence |")
    p("|----------|:----:|-------------|----------|")
    npass = nfail = 0
    for e in present:
        r = result_for(e["test"], qemu)
        npass += r.startswith("PASS")
        nfail += r.startswith("FAIL")
        p(row(e["block"], e["tier"], r, e.get("evidence", ""), e.get("caveat")))
    p("")
    p("## Absent IP — N/A (NOT a negative result)")
    p("")
    p("| IP block | Tier | Why absent |")
    p("|----------|:----:|-----------|")
    for e in absent:
        p(f"| {e['block']} | N/A | {e['reason']} |")
    p("")
    p(f"Summary: {len(present)} present "
      f"({npass} PASS / {nfail} FAIL observed this run), "
      f"{len(absent)} N/A-absent.")
    p("")

    text = "\n".join(lines) + "\n"
    if args.print:
        sys.stdout.write(text)
    else:
        open(args.out, "w").write(text)
        sys.stderr.write(f"wrote {args.out} "
                         f"({len(present)} present, {len(absent)} absent; "
                         f"{npass} PASS / {nfail} FAIL)\n")
    return 1 if nfail else 0


qemu_build_dir = "build"
if __name__ == "__main__":
    sys.exit(main())
