#!/usr/bin/env python3
# Copyright (c) 2026, Kyle Fox <kylefoxaustin@github>
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generate committed test vectors for the Ethos-U weight/scale decoders.
#
# Emits tests/unit/test-ethos-u-mlw-vectors.h, consumed by
# tests/unit/test-ethos-u-mlw.c.  The vectors are produced with the *installed*
# Arm Vela mlw_codec Python module (ethosu.mlw_codec) and Vela's encode_bias(),
# so the in-QEMU C decoder (hw/npu/mlw/mlw_decode.c) and reorder-inverse +
# scale/bias unpack (hw/npu/ethos_u_weights.c) are validated bit-for-bit against
# the reference implementation that compiled the firmware.
#
# Requires: numpy, ethosu.mlw_codec, ethosu.vela (pip install ethos-u-vela).
# Re-run after changing cases:  python3 tests/data/ethos-u/gen.py
#
# Each weight case: random OHWI int8 weights -> reorder_encode (NPU traversal
# order + mlw entropy encode) -> the encoded byte stream and the decoded flat
# stream are both captured; the C test decodes the bytes (must match flat) then
# runs reorder-inverse (must match the original OHWI).

import numpy as np
import ethosu.mlw_codec as mlw
from ethosu.vela.weight_compressor import encode_bias

OUT = "tests/unit/test-ethos-u-mlw-vectors.h"

# Ethos-U65-256 micro-block depths; ifm 8-bit; dilation 1 -> decomp 8x8.
IFM_UB = OFM_UB = 8
IFM_BD = 8
DH = DW = 8

WEIGHT_CASES = [
    # name,             ofm, kh, kw, ifm, ofm_block, depthwise, partkernel
    ("conv_depthfirst",  24, 3, 3, 20, 16, 0, 0),
    ("conv_partkernel",  24, 3, 3, 20, 16, 0, 1),
    ("depthwise",        20, 3, 3,  1, 16, 1, 0),
    ("conv_1x1",         16, 1, 1, 12, 16, 0, 0),
]


def c_u8_array(name, data):
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join("0x%02x" % b for b in data[i:i + 12])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return "\n".join(lines)


def c_i16_array(name, data):
    lines = [f"static const int16_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join("%d" % int(v) for v in data[i:i + 12])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    rng = np.random.default_rng(93)
    out = []
    out.append("/*")
    out.append(" * Auto-generated by tests/data/ethos-u/gen.py - do not edit.")
    out.append(" * Reference vectors from Arm Vela's ethosu.mlw_codec + encode_bias().")
    out.append(" *")
    out.append(" * SPDX-License-Identifier: GPL-2.0-or-later")
    out.append(" */")
    out.append("#ifndef TEST_ETHOS_U_MLW_VECTORS_H")
    out.append("#define TEST_ETHOS_U_MLW_VECTORS_H")
    out.append("")
    out.append("typedef struct {")
    out.append("    const char *name;")
    out.append("    int ifm_ublock, ofm_ublock;")
    out.append("    int ofm_depth, kh, kw, ifm_depth;")
    out.append("    int ofm_block_depth, is_depthwise, is_partkernel;")
    out.append("    int ifm_bitdepth, decomp_h, decomp_w;")
    out.append("    const uint8_t *enc; int enc_len;")
    out.append("    const int16_t *flat; int flat_len;")
    out.append("    const int16_t *ohwi; int ohwi_len;")
    out.append("} MlwWeightVec;")
    out.append("")

    entries = []
    for (name, ofm, kh, kw, ifm, ofmb, dw, pk) in WEIGHT_CASES:
        ohwi = rng.integers(-127, 128, size=(ofm, kh, kw, ifm), dtype=np.int16)
        enc, _plen = mlw.reorder_encode(IFM_UB, OFM_UB, ohwi, ofmb,
                                        dw, pk, IFM_BD, DH, DW)
        enc = bytes(enc)
        flat = np.array(mlw.decode(bytearray(enc)), dtype=np.int16)
        ohwi_flat = ohwi.reshape(-1)
        out.append(c_u8_array(f"{name}_enc", enc))
        out.append(c_i16_array(f"{name}_flat", flat))
        out.append(c_i16_array(f"{name}_ohwi", ohwi_flat))
        out.append("")
        entries.append(
            f'    {{ "{name}", {IFM_UB}, {OFM_UB}, {ofm}, {kh}, {kw}, {ifm}, '
            f'{ofmb}, {dw}, {pk}, {IFM_BD}, {DH}, {DW}, '
            f'{name}_enc, sizeof({name}_enc), '
            f'{name}_flat, ARRAY_SIZE({name}_flat), '
            f'{name}_ohwi, ARRAY_SIZE({name}_ohwi) }},')

    out.append("static const MlwWeightVec mlw_weight_vecs[] = {")
    out.extend(entries)
    out.append("};")
    out.append("")

    # ---- scale/bias 10-byte packing: [bias:40][scale:32][shift:6] LE ----
    out.append("typedef struct {")
    out.append("    int64_t bias; uint32_t scale; uint8_t shift;")
    out.append("    uint8_t packed[10];")
    out.append("} ScaleBiasVec;")
    out.append("")
    sb_cases = [
        (0, 0, 0),
        (1, 1, 1),
        (-1, 0xffffffff, 63),
        (123456789, 0x12345678, 17),
        (-(1 << 39), 0, 0),
        ((1 << 39) - 1, 0x7fffffff, 31),
        (-987654321, 1073741824, 5),
    ]
    out.append("static const ScaleBiasVec scale_bias_vecs[] = {")
    for (bias, scale, shift) in sb_cases:
        packed = bytes(encode_bias(np.int64(bias), int(scale), int(shift)))
        pk_str = ", ".join("0x%02x" % b for b in packed)
        out.append(f"    {{ {bias}LL, {scale}u, {shift}, "
                   f"{{ {pk_str} }} }},")
    out.append("};")
    out.append("")
    out.append("#endif /* TEST_ETHOS_U_MLW_VECTORS_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(WEIGHT_CASES)} weight + {len(sb_cases)} scale/bias vectors")


if __name__ == "__main__":
    main()
