#!/usr/bin/env python3
# Copyright (c) 2026, Kyle Fox <kylefoxaustin@github>
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Generate committed golden vectors for the Ethos-U fixed-point requantization
# (hw/npu/ethos_u_requant.c), emitting tests/unit/test-ethos-u-requant-vectors.h.
#
# The reference here is a faithful Python reimplementation of the gemmlowp /
# TensorFlow Lite Micro integer arithmetic (SaturatingRoundingDoublingHighMul,
# RoundingDivideByPOT, MultiplyByQuantizedMultiplier) that the Ethos-U datapath
# matches - it depends only on Python's bignum integers, no external packages,
# with explicit int32 wraparound so it tracks the C code bit-for-bit.
#
# Re-run after changing cases:  python3 tests/data/ethos-u/gen_requant.py

import math

OUT = "tests/unit/test-ethos-u-requant-vectors.h"
INT32_MIN = -(1 << 31)
INT32_MAX = (1 << 31) - 1


def i32(x):
    x &= 0xffffffff
    return x - (1 << 32) if x >= (1 << 31) else x


def ctrunc_div(n, d):
    """C integer division: truncate toward zero (d > 0)."""
    q = abs(n) // d
    return q if n >= 0 else -q


def srdhm(a, b):
    a, b = i32(a), i32(b)
    overflow = a == b == INT32_MIN
    ab = a * b
    nudge = (1 << 30) if ab >= 0 else (1 - (1 << 30))
    high = ctrunc_div(ab + nudge, 1 << 31)
    return INT32_MAX if overflow else i32(high)


def rdpot(x, exp):
    x = i32(x)
    if exp <= 0:
        return x
    assert exp <= 31
    mask = (1 << exp) - 1
    remainder = x & mask
    threshold = (mask >> 1) + (1 if x < 0 else 0)
    return (x >> exp) + (1 if remainder > threshold else 0)


def mul_by_quant_mult(x, mult, shift):
    left = shift if shift > 0 else 0
    right = 0 if shift > 0 else -shift
    return rdpot(srdhm(i32(x * (1 << left)), mult), right)


def quantise_scale(scale):
    """Vela scaling.quantise_scale: Q31 significand + (31 - exponent) shift."""
    significand, exponent = math.frexp(scale)
    # round away from zero
    s = significand * (1 << 31)
    significand_q31 = int(math.floor(s + 0.5)) if s >= 0 else int(math.ceil(s - 0.5))
    return significand_q31, 31 - exponent


def c_i32(v):
    if v == INT32_MIN:
        return "(-2147483647 - 1)"
    return "%d" % v


def main():
    out = []
    out.append("/*")
    out.append(" * Auto-generated by tests/data/ethos-u/gen_requant.py - do not edit.")
    out.append(" * gemmlowp / TFLite-Micro reference requantization golden vectors.")
    out.append(" *")
    out.append(" * SPDX-License-Identifier: GPL-2.0-or-later")
    out.append(" */")
    out.append("#ifndef TEST_ETHOS_U_REQUANT_VECTORS_H")
    out.append("#define TEST_ETHOS_U_REQUANT_VECTORS_H")
    out.append("")

    # --- SaturatingRoundingDoublingHighMul ---
    srdhm_in = [
        (0, 0), (1, 1), (-1, 1), (INT32_MAX, INT32_MAX),
        (INT32_MIN, INT32_MIN), (INT32_MIN, INT32_MAX),
        (1 << 30, 1 << 30), (-(1 << 30), 1 << 30),
        (1234567, 0x40000000), (-7654321, 0x7fffffff),
        (1000, -2000), (123456789, 987654321 & INT32_MAX),
    ]
    out.append("typedef struct { int32_t a, b, expected; } SrdhmVec;")
    out.append("static const SrdhmVec srdhm_vecs[] = {")
    for a, b in srdhm_in:
        out.append(f"    {{ {c_i32(a)}, {c_i32(b)}, {c_i32(srdhm(a, b))} }},")
    out.append("};")
    out.append("")

    # --- RoundingDivideByPOT ---
    rdpot_in = [
        (0, 0), (8, 1), (-8, 1), (7, 1), (-7, 1), (5, 2), (-5, 2),
        (1 << 20, 5), (-(1 << 20) - 1, 5), (3, 0), (INT32_MAX, 31),
        (INT32_MIN, 31), (12345, 4), (-12345, 4),
    ]
    out.append("typedef struct { int32_t x; int exp; int32_t expected; } RdpotVec;")
    out.append("static const RdpotVec rdpot_vecs[] = {")
    for x, e in rdpot_in:
        out.append(f"    {{ {c_i32(x)}, {e}, {c_i32(rdpot(x, e))} }},")
    out.append("};")
    out.append("")

    # --- MultiplyByQuantizedMultiplier (gemmlowp-style shift) ---
    mqm_in = [
        (1000, 0x40000000, 0), (1000, 0x40000000, -1), (1000, 0x40000000, -4),
        (-1000, 0x40000000, -4), (32767, 0x7fffffff, -8),
        (-32768, 0x7fffffff, -8), (1, 0x40000000, 2), (-1, 0x40000000, 2),
        (123456, 0x6f000000, -10), (-654321, 0x55555555, -12),
        (0, 0x40000000, -3), (2000000, 0x40000000, -20),
    ]
    out.append("typedef struct { int32_t x, mult; int shift; int32_t expected; }"
               " MqmVec;")
    out.append("static const MqmVec mqm_vecs[] = {")
    for x, m, s in mqm_in:
        out.append(f"    {{ {c_i32(x)}, {c_i32(i32(m))}, {s}, "
                   f"{c_i32(mul_by_quant_mult(x, i32(m), s))} }},")
    out.append("};")
    out.append("")

    # --- ethos_u_requant_vela: realistic (mult, vela_shift) from real scales ---
    # Typical conv output rescale = ifm_scale * weight_scale / ofm_scale (< 1).
    vela_scales = [0.5, 0.25, 0.013, 0.0009765625, 0.1234, 0.75, 0.003,
                   0.999, 0.0001]
    vela_x = [0, 1, -1, 1000, -1000, 50000, -50000, 1234567, -1234567]
    out.append("typedef struct { int32_t x; uint32_t mult; int vela_shift;"
               " int32_t expected; } VelaRequantVec;")
    out.append("static const VelaRequantVec vela_requant_vecs[] = {")
    for sc in vela_scales:
        mult, vshift = quantise_scale(sc)
        if not (0 <= vshift < (1 << 6)):
            continue
        for x in vela_x:
            exp = mul_by_quant_mult(x, i32(mult), 31 - vshift)
            out.append(f"    {{ {c_i32(x)}, {mult & 0xffffffff}u, {vshift}, "
                       f"{c_i32(exp)} }},")
    out.append("};")
    out.append("")
    out.append("#endif /* TEST_ETHOS_U_REQUANT_VECTORS_H */")

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(srdhm_in)} srdhm + {len(rdpot_in)} rdpot + "
          f"{len(mqm_in)} mqm vectors + vela cases")


if __name__ == "__main__":
    main()
